server:
  port: 8050

spring:
  application:
    name: menu
  datasource:
    name: waimai
    url: jdbc:mysql://localhost:3306/waimai?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.net.com.entity